import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRightIcon, ClockIcon, MapPinIcon, PhoneIcon } from "@heroicons/react/24/outline";
import { ContactForm } from "@/components/ContactForm";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";

export const metadata: Metadata = { title: "Contact Us | Mission Technology Solutions", description: "Talk with Mission Technology Solutions about managed IT, cybersecurity, networking, Microsoft 365, and physical security." };

export default function ContactPage() { return <main><SiteHeader /><section className="hero-motion relative overflow-hidden bg-mission-ink text-white"><Image src="/photos/managed-it-team.jpg" alt="Mission team collaborating in an office" fill priority sizes="100vw" className="object-cover opacity-25" /><div className="absolute inset-0 bg-mission-ink/80" /><div className="relative mx-auto max-w-7xl px-6 py-20 lg:px-8 lg:py-28"><div className="max-w-3xl"><p className="text-sm font-extrabold uppercase tracking-[0.18em] text-mission-gold">Contact Mission</p><h1 className="mt-5 text-5xl font-black tracking-tight sm:text-6xl lg:text-7xl">Let’s make your technology easier to run.</h1><p className="mt-7 text-lg leading-8 text-slate-300 sm:text-xl">Tell us what is working, what is frustrating, and what you want to improve. We’ll help you find the next practical step.</p></div></div></section><section className="bg-mission-mist py-16 lg:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-[0.75fr_1.25fr] lg:px-8"><div><p className="text-sm font-extrabold uppercase tracking-[0.18em] text-mission-navy">Start a conversation</p><h2 className="mt-3 text-4xl font-black tracking-tight text-mission-ink">A real person will follow up.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Whether you need a new IT partner, a second opinion, or help with one specific project, give us a little context and we’ll take it from there.</p><div className="mt-8 space-y-4"><a href="tel:+17652458515" className="flex items-center gap-3 font-bold text-mission-navy"><PhoneIcon className="h-5 w-5 text-mission-gold" />(765) 245-8515</a><div className="flex items-center gap-3 font-bold text-slate-700"><ClockIcon className="h-5 w-5 text-mission-gold" />Monday–Friday · 8:00 AM–5:00 PM</div><div className="flex items-center gap-3 font-bold text-slate-700"><MapPinIcon className="h-5 w-5 text-mission-gold" />Serving Kokomo and organizations across Indiana</div></div><Link href="/services" className="mt-8 inline-flex items-center gap-2 font-extrabold text-mission-navy">Explore our services <ArrowRightIcon className="h-4 w-4" /></Link></div><div className="rounded-3xl bg-white p-7 shadow-xl sm:p-10"><ContactForm /></div></div></section><section className="bg-mission-navy py-16 text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 px-6 lg:flex-row lg:items-center lg:px-8"><div><p className="text-sm font-extrabold uppercase tracking-[0.18em] text-mission-gold">Already a client?</p><h2 className="mt-2 text-3xl font-black">Need remote support?</h2></div><a href="https://missionts.rmmservices.net/connect/#/" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-mission-gold px-6 py-3.5 font-extrabold text-mission-ink">Open Remote Support <ArrowRightIcon className="h-4 w-4" /></a></div></section><SiteFooter /></main>; }
