import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeftIcon, CheckCircleIcon, ArrowRightIcon } from "@heroicons/react/24/outline";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";

const checklists: Record<string, { category: string; title: string; intro: string; items: string[] }> = {
  "security-baseline": { category: "Cybersecurity", title: "The practical security baseline", intro: "Use this as a first-pass review of the safeguards that protect people, systems, and customer trust.", items: ["Turn on multifactor authentication for every user and administrator.", "Confirm endpoint protection, patching, and encryption are active on every managed device.", "Review admin accounts and remove access people no longer need.", "Test backups by restoring a real file—not just checking that a job completed.", "Run a short phishing and incident-reporting refresher with staff.", "Write down who makes the call if an account, device, or mailbox is compromised."] },
  "microsoft-365-setup": { category: "Microsoft 365", title: "A calmer Microsoft 365 setup", intro: "A focused checklist for making Microsoft 365 easier to use and safer to manage.", items: ["Choose a clear naming and ownership pattern for Teams and SharePoint sites.", "Review guest access, external sharing, and inactive accounts.", "Standardize MFA, sign-in policies, and device enrollment.", "Define where files belong so staff are not emailing duplicate versions.", "Create retention, backup, and recovery expectations for critical data.", "Give users a short guide for Teams, OneDrive, and reporting suspicious messages."] },
  "proactive-it": { category: "Managed IT", title: "What proactive IT actually looks like", intro: "Use this checklist to see whether your IT program is preventing surprises—or simply reacting to them.", items: ["Maintain an accurate inventory of users, devices, software, and warranties.", "Patch operating systems, browsers, applications, and network equipment on a regular cadence.", "Review alerts and recurring tickets for patterns that deserve a permanent fix.", "Track device age and plan replacements before productivity is affected.", "Keep current diagrams, credentials, vendors, and escalation contacts documented.", "Hold a recurring roadmap conversation tied to business priorities and budget."] },
  "physical-security": { category: "Physical security", title: "Cameras and access control, connected", intro: "A practical walkthrough for planning a physical security system that works as one connected layer.", items: ["Map entrances, sensitive areas, delivery points, and after-hours activity.", "Choose camera views, retention, lighting, and privacy zones for each area.", "Confirm network, PoE, bandwidth, and power requirements before installation.", "Define door groups, schedules, visitor handling, and emergency access.", "Assign ownership for reviewing alerts, footage, and access events.", "Document device locations, serials, user roles, and maintenance expectations."] },
  "network-closet": { category: "Infrastructure", title: "A network closet field guide", intro: "A healthy closet is easier to support, safer to work in, and ready for the next project.", items: ["Label both ends of every cable and keep labels matched to a simple port map.", "Remove abandoned cabling and keep patching neat enough to trace quickly.", "Check rack power, UPS capacity, cooling, and physical access.", "Document switches, uplinks, VLANs, wireless access points, and camera runs.", "Test cable performance and fiber links after moves, adds, or changes.", "Leave clear space and a growth plan for the next device or service."] },
  "90-day-plan": { category: "Leadership", title: "Your next 90-day technology plan", intro: "Use this framework to turn a long list of technology concerns into an ordered, explainable plan.", items: ["List business-critical systems and the impact if each one fails.", "Separate urgent risk, productivity friction, and longer-term improvement.", "Choose three outcomes that matter most in the next 90 days.", "Assign an owner, rough cost, and target date to each priority.", "Schedule the small maintenance work that prevents larger surprises.", "Set a review date to measure progress and adjust the roadmap."] },
  "intune-business": { category: "Microsoft 365", title: "Why Is Intune Important for Your Business?", intro: "Microsoft Intune helps organizations manage, secure, and support devices wherever people work.", items: ["Enroll company devices so ownership, security, and support status are visible.", "Apply baseline settings for encryption, updates, screen locks, and approved applications.", "Separate business data from personal data on mobile devices.", "Use conditional access so risky or outdated devices cannot reach sensitive resources.", "Standardize onboarding and offboarding with repeatable device policies.", "Review compliance reports regularly and turn exceptions into an action list."] },
  "more-than-helpdesk": { category: "Managed IT", title: "Why a Good IT Firm Is More Than Just a Helpdesk", intro: "A strong IT partner resolves today’s issue while reducing the odds of the next one.", items: ["Look for proactive monitoring and maintenance, not only ticket response.", "Expect an accurate inventory, documentation, and lifecycle plan.", "Make security, backup, identity, and incident readiness part of the conversation.", "Ask how recommendations connect to business goals and budget.", "Set a recurring roadmap meeting to review priorities and progress.", "Choose a partner who can coordinate cloud, network, facilities, and vendors together."] },
  "edr-and-mdr": { category: "Cybersecurity", title: "What Are EDR and MDR?", intro: "EDR records and responds to suspicious activity on devices. MDR adds a team of analysts who watch, investigate, and help contain threats.", items: ["Confirm every supported endpoint reports to the EDR platform.", "Verify detections are reviewed by people—not left as unread alerts.", "Define who investigates, contains, communicates, and restores after an event.", "Test isolation and response workflows before a real incident.", "Review recurring detections for root causes and user coaching opportunities.", "Make sure reporting includes useful summaries for leadership and insurance reviews."] },
  "unique-passwords": { category: "Cybersecurity", title: "How You Can Protect Your Accounts with Unique Passwords", intro: "Unique passwords stop one breached website from becoming a key to every other account.", items: ["Use a different password for every business and personal account.", "Store passwords in a reputable password manager instead of a spreadsheet or browser note.", "Create long, memorable passphrases for the password manager itself.", "Turn on multifactor authentication, especially for email and financial systems.", "Remove shared passwords and assign individual accounts wherever possible.", "Review exposed or reused passwords and change them in priority order."] },
  "passkeys": { category: "Cybersecurity", title: "What Are Passkeys?", intro: "Passkeys let people sign in with a device, fingerprint, face, or PIN instead of typing a password that can be phished.", items: ["Identify the most important accounts where passkeys are supported.", "Enroll passkeys on managed devices and keep a secure recovery method.", "Teach users what a legitimate passkey prompt looks like.", "Keep MFA enabled while passkey adoption grows across the organization.", "Document how to remove a passkey when a device or employee changes.", "Review sign-in logs and recovery options as part of normal account hygiene."] },
  "managed-it-cost-per-user": { category: "Looking for IT", title: "What Does Managed IT Actually Cost Per User Per Month?", intro: "MSP pricing varies by coverage, security, complexity, and outcomes. Use this guide to compare the full value—not just the monthly number.", items: ["Ask exactly which users, devices, locations, and services are covered.", "Separate core support from security, backup, projects, licensing, and onsite work.", "Confirm after-hours coverage, response targets, and escalation expectations.", "Compare contract terms, annual increases, and offboarding fees.", "Estimate the cost of downtime and internal time spent coordinating vendors.", "Choose the proposal that makes scope and accountability easiest to understand."] },
  "break-fix-vs-managed": { category: "Looking for IT", title: "Break-Fix vs. Managed Services: The Real Math", intro: "The hourly rate is only part of the equation. Compare predictable service with downtime, recurring emergencies, and unplanned risk.", items: ["Review the last 12 months of invoices and emergency support time.", "Estimate lost productivity when systems or users are waiting on a fix.", "Add the cost of delayed maintenance, aging equipment, and security gaps.", "Compare that baseline with a managed plan’s recurring investment.", "Include planning, monitoring, documentation, and strategic guidance in the value.", "Revisit the comparison annually as your team and technology change."] },
  "managed-it-contract": { category: "Looking for IT", title: "What's Included in a Managed IT Contract (and What Usually Isn't)", intro: "A clear scope prevents surprises. Know what your monthly agreement covers before you sign.", items: ["Confirm helpdesk channels, hours, users, devices, and response targets.", "Ask whether monitoring, patching, endpoint security, and identity support are included.", "Clarify backup ownership, licensing, hardware, projects, and onsite visits.", "Review exclusions, after-hours rates, minimums, and third-party dependencies.", "Request a sample monthly report and roadmap meeting cadence.", "Make sure termination, data return, and documentation handoff are defined."] },
  "questions-for-an-msp": { category: "Looking for IT", title: "Questions to Ask Before Signing with an MSP", intro: "The right questions reveal how a provider communicates, manages risk, and takes ownership after the sale.", items: ["Who will support us day to day, and how do we reach them?", "How do you measure response, resolution, security, and customer satisfaction?", "What does your onboarding process look like in the first 30, 60, and 90 days?", "How do you handle incidents, vendors, projects, and after-hours emergencies?", "What will you document and review with leadership?", "Can we speak with a client who has a similar size or industry?"] },
  "outgrown-computer-guy": { category: "Looking for IT", title: "Signs You've Outgrown Your \"Computer Guy\"", intro: "Informal support can be a great start. Growth, risk, and compliance may signal that your business needs a more structured IT program.", items: ["Support depends on one person’s memory or availability.", "There is no current inventory, network map, security baseline, or recovery plan.", "Problems repeat because fixes are reactive instead of documented and preventive.", "Leadership lacks a technology roadmap, budget view, or risk summary.", "New hires, remote work, and vendors create more complexity than before.", "A provider can add process and depth without losing the personal relationship."] },
  "switch-msps-without-downtime": { category: "Looking for IT", title: "How to Switch MSPs Without Downtime", intro: "A thoughtful transition protects continuity, access, and trust while a new provider learns your environment.", items: ["Review your agreement, notice period, ownership, and documentation rights.", "Select a new provider before ending the old relationship.", "Build a transition plan for credentials, agents, backups, vendors, and open issues.", "Schedule the handoff around business-critical dates and change windows.", "Validate monitoring, security, backups, and support channels before cutover.", "Keep a shared issue log and executive check-in through the first 30 days."] },
  "what-is-a-vcio": { category: "Looking for IT", title: "What Does a vCIO Do and When Does a Small Business Need One?", intro: "A virtual CIO brings strategic technology leadership without the cost of a full-time executive.", items: ["Connect technology priorities to revenue, operations, risk, and customer commitments.", "Build a roadmap with sequencing, owners, budget ranges, and business outcomes.", "Translate technical risk into decisions leadership can act on.", "Coordinate security, cloud, network, vendors, and lifecycle planning.", "Set a recurring cadence for reporting and adjusting priorities.", "Consider vCIO support when growth or complexity outpaces informal planning."] },
  "co-managed-it": { category: "Looking for IT", title: "Co-Managed IT: How It Works When You Already Have Internal Staff", intro: "Co-managed IT adds capacity and specialized expertise while your internal team keeps the relationships and context it owns best.", items: ["List the responsibilities your internal team wants to keep, share, or delegate.", "Define clear ownership for tickets, projects, security, vendors, and escalation.", "Choose a shared documentation and communication system.", "Use the MSP for coverage, deep expertise, tooling, or strategic capacity gaps.", "Review workload, service levels, and priorities together on a regular cadence.", "Adjust the partnership as hiring, projects, and business needs change."] },
  "msp-vs-internal-it": { category: "Looking for IT", title: "MSP vs. Hiring an Internal IT Person: Cost Comparison", intro: "Compare total coverage and capability—not just salary—when deciding between an MSP and an internal hire.", items: ["Include salary, benefits, recruiting, training, tools, and backup coverage.", "Compare the breadth of security, networking, cloud, and compliance expertise available.", "Account for vacations, sick time, after-hours needs, and single-person dependency.", "Estimate how quickly each option can deliver projects and strategic planning.", "Consider a hybrid model if your team needs both an internal owner and outside depth.", "Recalculate the decision as headcount, locations, and risk change."] },
  "it-onboarding-transition": { category: "Looking for IT", title: "What Happens During an IT Onboarding/Transition?", intro: "A good onboarding turns a new relationship into a documented, secure, and predictable operating rhythm.", items: ["Meet stakeholders and learn the business, priorities, and pain points.", "Discover users, devices, applications, networks, vendors, and critical systems.", "Secure access, deploy monitoring, and verify backups and endpoint protection.", "Document the environment, risks, lifecycle needs, and quick wins.", "Set communication channels, ticket expectations, reporting, and roadmap cadence.", "Review progress at 30, 60, and 90 days and agree on the next priorities."] },
};

const localGuides: Record<string, { category: string; title: string; intro: string; items: string[] }> = {
  "it-support-kokomo": { category: "Local resources", title: "IT Support in Kokomo, Indiana", intro: "A local guide to choosing responsive managed IT, cybersecurity, networking, and technology support in Kokomo.", items: ["List the systems and locations your team depends on every day.", "Confirm your provider can support Microsoft 365, endpoints, networks, and security together.", "Ask how quickly local and remote issues are acknowledged and escalated.", "Review backup, incident response, and lifecycle planning—not just ticket support.", "Look for experience with organizations similar to yours in Howard County.", "Set a roadmap conversation around your next business priorities."] },
  "it-support-tipton": { category: "Local resources", title: "IT Support in Tipton, Indiana", intro: "Practical technology support for Tipton businesses and organizations that need a responsive local partner.", items: ["Document users, devices, locations, and critical applications.", "Verify monitoring, patching, MFA, and endpoint protection are included.", "Ask about onsite response and vendor coordination when needed.", "Confirm backup testing and recovery expectations.", "Review communication and reporting cadence.", "Choose a partner who can scale as your needs change."] },
  "it-support-peru": { category: "Local resources", title: "IT Support in Peru, Indiana", intro: "Managed IT and infrastructure guidance for Peru businesses, nonprofits, and public organizations.", items: ["Identify critical workflows and technology pain points.", "Review network, wireless, cabling, and internet resilience.", "Confirm security awareness, MFA, and incident response practices.", "Ask how documentation and onboarding are handled.", "Compare predictable support with emergency-only costs.", "Create a 90-day improvement plan."] },
  "it-support-logansport": { category: "Local resources", title: "IT Support in Logansport, Indiana", intro: "A practical starting point for finding dependable IT support and security in Logansport.", items: ["Inventory devices, accounts, applications, and vendors.", "Check patching, encryption, backups, and access controls.", "Set clear response targets for urgent and routine issues.", "Ask for a lifecycle and budget roadmap.", "Confirm support for remote users and multiple locations.", "Review results and priorities quarterly."] },
  "it-support-noblesville": { category: "Local resources", title: "IT Support in Noblesville, Indiana", intro: "Scalable managed IT and cybersecurity considerations for growing Noblesville businesses.", items: ["Plan for onboarding, growth, and role-based access.", "Standardize devices, applications, and security policies.", "Review cloud, network, and identity architecture.", "Confirm proactive monitoring and after-hours coverage.", "Ask how projects and vendors are coordinated.", "Tie technology investments to growth goals."] },
  "it-support-westfield": { category: "Local resources", title: "IT Support in Westfield, Indiana", intro: "Reliable technology support for Westfield offices, practices, and organizations.", items: ["Map locations, users, devices, and business-critical systems.", "Confirm reliable Wi-Fi, network segmentation, and backup connectivity.", "Review MFA, endpoint security, and phishing readiness.", "Set ticket, onsite, and escalation expectations.", "Keep documentation current and accessible.", "Review a prioritized technology roadmap."] },
  "it-support-carmel": { category: "Local resources", title: "IT Support in Carmel, Indiana", intro: "Strategic managed IT and security guidance for Carmel businesses that expect more from technology.", items: ["Define business outcomes technology should improve.", "Assess identity, cloud, endpoint, and network controls.", "Ask how reporting translates risk into leadership decisions.", "Confirm project planning, budgeting, and vendor management.", "Test backups and incident response before an emergency.", "Review progress against a shared roadmap."] },
  "it-support-lafayette": { category: "Local resources", title: "IT Support in Lafayette, Indiana", intro: "Connected, secure, and dependable IT support considerations for Lafayette organizations.", items: ["Identify critical systems and connectivity dependencies.", "Review internet, Wi-Fi, cabling, and network resilience.", "Confirm endpoint, email, and identity protections.", "Ask about local coverage and remote response.", "Document vendors, credentials, and recovery steps.", "Prioritize improvements by business impact."] },
  "howard-county-internet": { category: "Local resources", title: "Business Internet Options in Howard County: Who Actually Delivers What", intro: "Availability varies by address. Use this guide to compare business internet providers, service levels, and real-world fit.", items: ["Check service availability at each exact business address.", "Compare upload speeds, static IPs, SLAs, and repair commitments.", "Ask about fiber, cable, fixed wireless, and backup options.", "Confirm installation timelines, contract terms, and price increases.", "Plan failover for phones, cloud applications, and critical operations.", "Have a network professional validate the proposal before signing."] },
  "indiana-breach-notification": { category: "Local resources", title: "Indiana Data Breach Notification Law: What Small Businesses Must Do", intro: "When personal information may be exposed, Indiana businesses should move quickly, preserve facts, and coordinate legal and technical response.", items: ["Activate your incident response contacts and preserve relevant evidence.", "Determine what information and Indiana residents may be affected.", "Engage qualified legal counsel to assess notification obligations and timing.", "Contain compromised accounts, devices, and systems while investigating scope.", "Coordinate required notices and communications with counsel.", "Document decisions, remediation, and lessons learned."] },
  "indiana-tech-grants": { category: "Local resources", title: "Local Resources for Indiana Small Business Tech Grants", intro: "Funding programs change, but a clear project plan makes it easier to identify and apply for technology support.", items: ["Define the business problem, project scope, and measurable outcome.", "Check Indiana, county, city, utility, and economic development resources.", "Confirm eligibility, match requirements, deadlines, and eligible expenses.", "Gather quotes, budgets, cybersecurity plans, and business registration documents.", "Show how the project improves resilience, jobs, productivity, or growth.", "Track award conditions, reporting, and procurement requirements."] },
};
Object.assign(checklists, localGuides);

export function generateStaticParams() { return Object.keys(checklists).map((slug) => ({ slug })); }
export function generateMetadata({ params }: { params: { slug: string } }): Metadata { const guide = checklists[params.slug]; return { title: guide ? `${guide.title} | Mission Knowledge Hub` : "Mission Knowledge Hub", description: guide?.intro }; }

export default function ChecklistPage({ params }: { params: { slug: string } }) {
  const guide = checklists[params.slug] ?? checklists["security-baseline"];
  return <main><SiteHeader /><section className="bg-mission-ink py-20 text-white lg:py-28"><div className="mx-auto max-w-4xl px-6 lg:px-8"><Link href="/resources" className="inline-flex items-center gap-2 text-sm font-bold text-slate-300 hover:text-mission-gold"><ArrowLeftIcon className="h-4 w-4" /> Back to Knowledge Hub</Link><p className="mt-10 text-sm font-extrabold uppercase tracking-[0.18em] text-mission-gold">{guide.category} checklist</p><h1 className="mt-4 text-5xl font-black tracking-tight sm:text-6xl">{guide.title}</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-slate-300">{guide.intro}</p></div></section><section className="bg-mission-mist py-16 lg:py-24"><div className="mx-auto max-w-4xl px-6 lg:px-8"><div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm sm:p-10"><div className="flex items-center gap-3"><CheckCircleIcon className="h-7 w-7 text-mission-gold" /><h2 className="text-2xl font-black text-mission-ink">Work through these one at a time</h2></div><div className="mt-8 grid gap-4">{guide.items.map((item, index) => <div key={item} className="flex gap-4 rounded-2xl border border-slate-200 p-5"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-mission-navy text-sm font-black text-white">{index + 1}</div><p className="font-bold leading-7 text-slate-700">{item}</p></div>)}</div></div><div className="mt-8 rounded-3xl bg-mission-navy p-8 text-white"><p className="text-sm font-extrabold uppercase tracking-[0.18em] text-mission-gold">Want a second set of eyes?</p><h2 className="mt-3 text-3xl font-black">Mission can help turn this checklist into a plan.</h2><Link href="/#contact" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-mission-gold px-6 py-3.5 font-extrabold text-mission-ink">Talk with Mission <ArrowRightIcon className="h-4 w-4" /></Link></div></div></section><SiteFooter /></main>;
}
