import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeftIcon, CheckCircleIcon, ArrowRightIcon } from "@heroicons/react/24/outline";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";

const checklists: Record<string, { category: string; title: string; intro: string; items: string[] }> = {
  "security-baseline": { category: "Cybersecurity", title: "The practical security baseline", intro: "Use this as a first-pass review of the safeguards that protect people, systems, and customer trust.", items: ["Turn on multifactor authentication for every user and administrator.", "Confirm endpoint protection, patching, and encryption are active on every managed device.", "Review admin accounts and remove access people no longer need.", "Test backups by restoring a real file—not just checking that a job completed.", "Run a short phishing and incident-reporting refresher with staff.", "Write down who makes the call if an account, device, or mailbox is compromised."] },
  "microsoft-365-setup": { category: "Microsoft 365", title: "A calmer Microsoft 365 setup", intro: "A focused checklist for making Microsoft 365 easier to use and safer to manage.", items: ["Choose a clear naming and ownership pattern for Teams and SharePoint sites.", "Review guest access, external sharing, and inactive accounts.", "Standardize MFA, sign-in policies, and device enrollment.", "Define where files belong so staff are not emailing duplicate versions.", "Create retention, backup, and recovery expectations for critical data.", "Give users a short guide for Teams, OneDrive, and reporting suspicious messages."] },
  "proactive-it": { category: "Managed IT", title: "What proactive IT actually looks like", intro: "Use this checklist to see whether your IT program is preventing surprises—or simply reacting to them.", items: ["Maintain an accurate inventory of users, devices, software, and warranties.", "Patch operating systems, browsers, applications, and network equipment on a regular cadence.", "Review alerts and recurring tickets for patterns that deserve a permanent fix.", "Track device age and plan replacements before productivity is affected.", "Keep current diagrams, credentials, vendors, and escalation contacts documented.", "Hold a recurring roadmap conversation tied to business priorities and budget."] },
  "physical-security": { category: "Physical security", title: "Cameras and access control, connected", intro: "A practical walkthrough for planning a physical security system that works as one connected layer.", items: ["Map entrances, sensitive areas, delivery points, and after-hours activity.", "Choose camera views, retention, lighting, and privacy zones for each area.", "Confirm network, PoE, bandwidth, and power requirements before installation.", "Define door groups, schedules, visitor handling, and emergency access.", "Assign ownership for reviewing alerts, footage, and access events.", "Document device locations, serials, user roles, and maintenance expectations."] },
  "network-closet": { category: "Infrastructure", title: "A network closet field guide", intro: "A healthy closet is easier to support, safer to work in, and ready for the next project.", items: ["Label both ends of every cable and keep labels matched to a simple port map.", "Remove abandoned cabling and keep patching neat enough to trace quickly.", "Check rack power, UPS capacity, cooling, and physical access.", "Document switches, uplinks, VLANs, wireless access points, and camera runs.", "Test cable performance and fiber links after moves, adds, or changes.", "Leave clear space and a growth plan for the next device or service."] },
  "90-day-plan": { category: "Leadership", title: "Your next 90-day technology plan", intro: "Use this framework to turn a long list of technology concerns into an ordered, explainable plan.", items: ["List business-critical systems and the impact if each one fails.", "Separate urgent risk, productivity friction, and longer-term improvement.", "Choose three outcomes that matter most in the next 90 days.", "Assign an owner, rough cost, and target date to each priority.", "Schedule the small maintenance work that prevents larger surprises.", "Set a review date to measure progress and adjust the roadmap."] },
};

export function generateStaticParams() { return Object.keys(checklists).map((slug) => ({ slug })); }
export function generateMetadata({ params }: { params: { slug: string } }): Metadata { const guide = checklists[params.slug]; return { title: guide ? `${guide.title} | Mission Knowledge Hub` : "Mission Knowledge Hub", description: guide?.intro }; }

export default function ChecklistPage({ params }: { params: { slug: string } }) {
  const guide = checklists[params.slug] ?? checklists["security-baseline"];
  return <main><SiteHeader /><section className="bg-mission-ink py-20 text-white lg:py-28"><div className="mx-auto max-w-4xl px-6 lg:px-8"><Link href="/resources" className="inline-flex items-center gap-2 text-sm font-bold text-slate-300 hover:text-mission-gold"><ArrowLeftIcon className="h-4 w-4" /> Back to Knowledge Hub</Link><p className="mt-10 text-sm font-extrabold uppercase tracking-[0.18em] text-mission-gold">{guide.category} checklist</p><h1 className="mt-4 text-5xl font-black tracking-tight sm:text-6xl">{guide.title}</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-slate-300">{guide.intro}</p></div></section><section className="bg-mission-mist py-16 lg:py-24"><div className="mx-auto max-w-4xl px-6 lg:px-8"><div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm sm:p-10"><div className="flex items-center gap-3"><CheckCircleIcon className="h-7 w-7 text-mission-gold" /><h2 className="text-2xl font-black text-mission-ink">Work through these one at a time</h2></div><div className="mt-8 grid gap-4">{guide.items.map((item, index) => <div key={item} className="flex gap-4 rounded-2xl border border-slate-200 p-5"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-mission-navy text-sm font-black text-white">{index + 1}</div><p className="font-bold leading-7 text-slate-700">{item}</p></div>)}</div></div><div className="mt-8 rounded-3xl bg-mission-navy p-8 text-white"><p className="text-sm font-extrabold uppercase tracking-[0.18em] text-mission-gold">Want a second set of eyes?</p><h2 className="mt-3 text-3xl font-black">Mission can help turn this checklist into a plan.</h2><Link href="/#contact" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-mission-gold px-6 py-3.5 font-extrabold text-mission-ink">Talk with Mission <ArrowRightIcon className="h-4 w-4" /></Link></div></div></section><SiteFooter /></main>;
}
